language: node_js
node_js:
- '10.15'
cache:
  yarn: true
script:
# - yarn lint
- yarn test
deploy:
  provider: heroku
  api_key:
    secure: nwAt2tSWr7C9zH0zFTjTb46WHOJIjYkENvHxTbP2MEBm3eKdHZA5YFrLNFqov4bxS99paP30icGHStdHhrIcPKitRNh/D+HWK7uaZQi6DGrQeWVhkWCeYHhOr9QliW8Tdzsqb8rvAUw63eGUycVZuFXtGBELpAcC7dVaM6Gjfd48lrZ04Umeg9gDYgyzXUS8k5uSiVRMQAF9wm9gZn/FoUaQ8IViEqHGUZcVRFUOSQ6UhrYF+2XoYDJ00hag19pbmfuBOFUmtc+UxO/DCPqIRelqjJyBgUSjMvj2BmcHNiLl8rxwj6+x9umwo5Ygm1k1eI6X9Ivj2cwO3FBB6QkDh0bjg8jlZ4xmpHP856eS9hER0axpJbhpO7E/oeqUcX4Vzz1kUshS2wN+C12zXzGDLBBiyu4nSoc0TXr7kFKMTnpwIIyX3iFnbu1rSe1Mfz8BS6R+D/n+rYowgnuTH4+Hn92KHTzvA5PBeRp4qy5w7E+rn7YiQP1j396u7tpUpcemRZjX6Rf1Z7CR5cqZlPTz+S8DRVnTFQPCk6nyKv3hjs3cIvAOaBA5K81O888d8uceXtMvCstWn3o/F7HF7jId3hcHzPPJgMZM9Y4y/fvgG0OwCIjSexpieUBsnZWkrhileorpJYZDaOnwP3x+J4VIR7hAQFSWJiHvuSiBytKHdmg=
  app: caribbeancinemas-api
