version: "3"

services:
  web:
    build: .
    command: yarn run build
    volumes:
      - ./dist:/app/dist
    ports:
      - "3000:3000"
    env:
      - NODE_ENV="docker"
      - DATABASE_HOST="database"

  worker:
    build: .
    command: yarn run tasks
    volumes:
      - ./dist:/app/dist
    env:
      - NODE_ENV="docker"
      - DATABASE_HOST="database"


  database:
    image: mongo:4.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password